name: Build & Push to Docker Hub (multi-arch)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "bs4fix*" ]
  schedule:
    # täglich 03:10 UTC
    - cron: "10 3 * * *"
  workflow_dispatch:

concurrency:
  group: dockerhub-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO: docker.io/railsimulatornet/new-easyepg

jobs:
  # 1) Nur bauen, wenn es was Neues gibt (Base-Digest oder PyPI-Patchrelease)
  check:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.decide.outputs.should_build }}
      fingerprint:  ${{ steps.fingerprint.outputs.value }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute update fingerprint (base digest + latest patch versions)
        id: fingerprint
        shell: bash
        run: |
          set -euo pipefail

          BASE="python:3.12-slim"
          # Digest des Base-Images ziehen
          DIGEST="$(docker buildx imagetools inspect "${BASE}" | awk -F': ' '/Digest:/ {print $2; exit}')"

          # Aus requirements.txt "~=" Constraints lesen und jeweils neuestes Patch-Release ermitteln
          python <<'PY' > /tmp/pip-latest.txt
          import re, json, urllib.request
          out = []
          with open("requirements.txt", encoding="utf-8") as f:
              for line in f:
                  line = line.strip()
                  if not line or line.startswith("#"):
                      continue
                  m = re.match(r'([A-Za-z0-9_.-]+)\s*~=\s*([0-9]+)\.([0-9]+)', line)
                  if not m:
                      continue
                  name = m.group(1)
                  minor = f"{m.group(2)}.{m.group(3)}"
                  url  = f"https://pypi.org/pypi/{name}/json"
                  with urllib.request.urlopen(url) as r:
                      data = json.load(r)
                  versions = [v for v in data["releases"].keys() if v.startswith(minor + ".")]
                  def key(v):
                      parts = re.split(r'(\d+)', v)
                      return [int(p) if p.isdigit() else p for p in parts]
                  latest = sorted(versions, key=key)[-1] if versions else data["info"]["version"]
                  out.append(f"{name}={latest}")
          print(";".join(out))
          PY

          PIP_FP="$(cat /tmp/pip-latest.txt)"
          FP="base=${DIGEST};${PIP_FP}"
          echo "value=${FP}" >> "${GITHUB_OUTPUT}"

      - name: Cache by fingerprint (skip build if unchanged)
        id: cache
        uses: actions/cache@v4
        with:
          path: .fp-cache/fingerprint
          key: update-fp-${{ steps.fingerprint.outputs.value }}

      - name: Decide to build or skip
        id: decide
        shell: bash
        run: |
          if [[ "${{ steps.cache.outputs.cache-hit }}" == "true" ]]; then
            echo "No changes detected."
            echo "should_build=false" >> "${GITHUB_OUTPUT}"
          else
            mkdir -p .fp-cache
            echo "${{ steps.fingerprint.outputs.value }}" > .fp-cache/fingerprint
            echo "Changes detected -> build"
            echo "should_build=true" >> "${GITHUB_OUTPUT}"
          fi

  build-arch:
    needs: check
    if: needs.check.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.amd64
            platform: linux/amd64
            suffix: amd64
          - dockerfile: Dockerfile.arm64v8
            platform: linux/arm64
            suffix: arm64
          - dockerfile: Dockerfile.arm32v7
            platform: linux/arm/v7
            suffix: armv7
    steps:
      - uses: actions/checkout@v4

      - name: Strip legacy qemu/cross-build lines (ARM Dockerfiles)
        shell: bash
        run: |
          for f in Dockerfile.arm64v8 Dockerfile.arm32v7; do
            [[ -f "$f" ]] || continue
            sed -i '/qemu-.*-static/d;/QEMU_EXECVE/d;/cross-build-start/d;/cross-build-end/d' "$f" || true
          done

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REPO }}:bs4fix-${{ matrix.suffix }}
            ${{ env.REPO }}:${{ github.sha }}-${{ matrix.suffix }}
          cache-from: type=registry,ref=${{ env.REPO }}:cache-${{ matrix.suffix }}
          cache-to:   type=registry,mode=max,ref=${{ env.REPO }}:cache-${{ matrix.suffix }}

  manifest:
    needs: build-arch
    if: needs.check.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push multi-arch manifest (:bs4fix)
        env:
          REPO: ${{ env.REPO }}
        run: |
          docker buildx imagetools create \
            -t "$REPO:bs4fix" \
            "$REPO:bs4fix-amd64" \
            "$REPO:bs4fix-arm64" \
            "$REPO:bs4fix-armv7"

      - name: Create & Push manifest for git tag
        if: startsWith(github.ref, 'refs/tags/')
        env:
          REPO: ${{ env.REPO }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          docker buildx imagetools create \
            -t "$REPO:${TAG}" \
            "$REPO:bs4fix-amd64" \
            "$REPO:bs4fix-arm64" \
            "$REPO:bs4fix-armv7"

      - name: Also tag :latest on main
        if: github.ref == 'refs/heads/main'
        env:
          REPO: ${{ env.REPO }}
        run: |
          docker buildx imagetools create \
            -t "$REPO:latest" \
            "$REPO:bs4fix-amd64" \
            "$REPO:bs4fix-arm64" \
            "$REPO:bs4fix-armv7"
