name: Build & Push to Docker Hub (multi-arch)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "bs4fix*" ]
  schedule:
    # Jeden Montag 03:00 UTC (anpassen wie du willst)
    - cron:  '0 3 * * 1'
  workflow_dispatch:

concurrency:
  group: dockerhub-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO: docker.io/railsimulatornet/new-easyepg

jobs:
  build-arch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.amd64
            platform: linux/amd64
            suffix: amd64
          - dockerfile: Dockerfile.arm64v8
            platform: linux/arm64
            suffix: arm64
          - dockerfile: Dockerfile.arm32v7
            platform: linux/arm/v7
            suffix: armv7

    steps:
      - uses: actions/checkout@v4

      # Entfernt alte Cross-Build/Static-QEMU-Zeilen,
      # damit Buildx/QEMU sauber arbeitet und dein früherer Fehler nicht auftritt.
      - name: Strip legacy qemu/cross-build lines (ARM Dockerfiles)
        run: |
          for f in Dockerfile.arm64v8 Dockerfile.arm32v7; do
            [[ -f "$f" ]] || continue
            sed -i '/qemu-.*-static/d;/QEMU_EXECVE/d;/cross-build-start/d;/cross-build-end/d' "$f" || true
          done
          echo "Patched Dockerfiles (if needed)."

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          # Fix-Tag + zusätzlich commit-spezifischer Tag zum Nachvollziehen
          tags: |
            ${{ env.REPO }}:bs4fix-${{ matrix.suffix }}
            ${{ env.REPO }}:${{ github.sha }}-${{ matrix.suffix }}
          cache-from: type=registry,ref=${{ env.REPO }}:cache-${{ matrix.suffix }}
          cache-to:   type=registry,mode=max,ref=${{ env.REPO }}:cache-${{ matrix.suffix }}

  manifest:
    needs: build-arch
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push multi-arch manifest (:bs4fix)
        run: |
          docker buildx imagetools create \
            -t $REPO:bs4fix \
            $REPO:bs4fix-amd64 \
            $REPO:bs4fix-arm64 \
            $REPO:bs4fix-armv7
        env:
          REPO: ${{ env.REPO }}

      # Optional: bei Tags zusätzlich auch das Tag als Manifest veröffentlichen (v0.x, bs4fix-xyz, ...)
      - name: Create & Push manifest for git tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          docker buildx imagetools create \
            -t $REPO:${TAG} \
            $REPO:bs4fix-amd64 \
            $REPO:bs4fix-arm64 \
            $REPO:bs4fix-armv7
        env:
          REPO: ${{ env.REPO }}

      # Zusätzlich :latest auf main aktualisieren
      - name: Also tag :latest on main
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx imagetools create \
            -t $REPO:latest \
            $REPO:bs4fix-amd64 \
            $REPO:bs4fix-arm64 \
            $REPO:bs4fix-armv7
        env:
          REPO: ${{ env.REPO }}
