name: Build & Push to Docker Hub (multi-arch)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "bs4fix*" ]
  workflow_dispatch:

env:
  IMAGE_NAME: new-easyepg
  REPO: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/new-easyepg

jobs:
  build-arch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.amd64
            platform: linux/amd64
            suffix: amd64
          - dockerfile: Dockerfile.arm64v8
            platform: linux/arm64
            suffix: arm64
          - dockerfile: Dockerfile.arm32v7
            platform: linux/arm/v7
            suffix: armv7
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REPO }}:bs4fix-${{ matrix.suffix }}
            ${{ env.REPO }}:${{ github.sha }}-${{ matrix.suffix }}
          cache-from: type=registry,ref=${{ env.REPO }}:cache-${{ matrix.suffix }}
          cache-to: type=registry,mode=max,ref=${{ env.REPO }}:cache-${{ matrix.suffix }}

  manifest:
    needs: build-arch
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create & Push multi-arch manifest (:bs4fix)
        run: |
          docker buildx imagetools create \
            -t $REPO:bs4fix \
            $REPO:bs4fix-amd64 \
            $REPO:bs4fix-arm64 \
            $REPO:bs4fix-armv7
        env:
          REPO: ${{ env.REPO }}

      - name: Also tag :latest on main
        if: github.ref == 'refs/heads/main'
        run: |
          docker buildx imagetools create \
            -t $REPO:latest \
            $REPO:bs4fix-amd64 \
            $REPO:bs4fix-arm64 \
            $REPO:bs4fix-armv7
        env:
          REPO: ${{ env.REPO }}
